#!/usr/bin/env node
// Builds the forge worker card from forge-principles/SKILL.md: a fixed preface plus
// the bold first line of every numbered rule. Deterministic: same SKILL.md, same bytes.
//
//   node scripts/card.mjs            print the card
//   node scripts/card.mjs --write    write references/worker-card.md
//   node scripts/card.mjs --check    exit 1 when the committed card is stale

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SKILL_DIR = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL_PATH = join(SKILL_DIR, 'SKILL.md');
export const CARD_PATH = join(SKILL_DIR, 'references', 'worker-card.md');

const PREFACE =
  "Forge worker card: do this ticket's job, nothing next to it. " +
  'Full rules: the forge-principles skill.';

export function extractRules(skillMd) {
  const start = skillMd.indexOf('\n## Rules\n');
  if (start === -1) throw new Error('SKILL.md has no "## Rules" section');
  const after = skillMd.slice(start + 1);
  const next = after.slice(1).search(/\n## /);
  const section = next === -1 ? after : after.slice(0, next + 1);
  const rules = [];
  const re = /^### \d+\. (.+)\n\n?\*\*(.+?)\*\*[ \t]*$/gm;
  for (const m of section.matchAll(re)) rules.push({ title: m[1].trim(), lead: m[2].trim() });
  if (rules.length === 0) throw new Error('no "### N. Title" + bold lead pairs found under ## Rules');
  return rules;
}

export function buildCard(skillMd) {
  const hash = createHash('sha256').update(skillMd).digest('hex').slice(0, 12);
  const lines = extractRules(skillMd).map((r) => `- ${r.title}: ${r.lead}`);
  return [
    `<!-- generated by forge-principles/scripts/card.mjs from SKILL.md sha256:${hash}; do not edit -->`,
    PREFACE,
    '',
    ...lines,
    '',
  ].join('\n');
}

export function cardWords(card) {
  return card
    .split('\n')
    .filter((l) => !l.startsWith('<!--'))
    .join(' ')
    .split(/\s+/)
    .filter((w) => /\w/.test(w)).length;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const card = buildCard(readFileSync(SKILL_PATH, 'utf8'));
  if (process.argv.includes('--write')) {
    writeFileSync(CARD_PATH, card);
    console.log(`wrote ${CARD_PATH} (${cardWords(card)} words)`);
  } else if (process.argv.includes('--check')) {
    const current = existsSync(CARD_PATH) ? readFileSync(CARD_PATH, 'utf8') : '';
    if (current !== card) {
      console.error('worker-card.md is stale. Run: node skills/forge-principles/scripts/card.mjs --write');
      process.exit(1);
    }
    console.log(`worker-card.md is current (${cardWords(card)} words)`);
  } else {
    process.stdout.write(card);
  }
}
